Repository builtree/simulate, pull requests merged in 2020-03, with the labels that each got.

#94 Updated README
  README.md
Labels: beginner, documentation, gssoc20

#103 lib: src: migrated screen_util and provider
  lib/main.dart
  lib/src/simulations/bubble_sort.dart
  lib/src/simulations/epicycloid_curve.dart
  lib/src/simulations/fourier_series.dart
  lib/src/simulations/insertion_sort.dart
  lib/src/simulations/lissajous_curve.dart
  lib/src/simulations/rose_pattern.dart
  lib/src/simulations/toothpick.dart
Labels: easy, gssoc20

#86 Update pubspec.yaml
  pubspec.yaml
Labels: beginner, enhancement, gssoc20
